### ISSUE TITLE
read_excel crashes when table destinations is a numeric value

### ISSUE THREAD

**Issue by kevarding** [startable/pdtable#145]
This issue occurs when reading startables from an Excel file (.xlsx) if one of the tables destinations is a single integer value.

An example table would be:

| **table | |
| --- | --- |
|1 | |
| col1 | col2 |
| - | text |
| 1 | a |
| 2 | b |

(See attached file: [simple_example.xlsx](https://github.com/user-attachments/files/15739139/simple_example.xlsx))

Reading in the above file using the following code
```
from pdtable import read_excel

list(read_excel("./simple_example.xlsx"))
```

Throws the following error:
```
Traceback (most recent call last):
  File ".\example.py", line 3, in <module>
    tables = list(read_excel("./simple_example.xlsx"))
  File "...\pdtable\io\excel.py", line 107, in read_excel
    issue_tracker=issue_tracker,
  File "...\pdtable\io\parsers\blocks.py", line 367, in parse_blocks
    issue_tracker=issue_tracker,
  File "...\pdtable\io\parsers\blocks.py", line 489, in parse_blocks_stable
    yield from block_output(state, cell_grid, this_block_1st_row)
  File "...\pdtable\io\parsers\blocks.py", line 445, in block_output
    block = handler(cell_grid, origin=origin, fixer=fixer)
  File "...\pdtable\io\parsers\blocks.py", line 212, in _make_table
    cells, origin=str(origin.input_location), fixer=fixer,
  File "...\pdtable\io\parsers\blocks.py", line 123, in make_table_json_precursor
    destinations = {dest: None for dest in cells[1][0].strip().split(" ")}
AttributeError: 'int' object has no attribute 'strip'
```
This does not occur when reading in the same table from a `.csv`.file.

**Comment by kevarding** [comment]
It would seem that `cells[1][0]` is assumed to be of `str`-type, which is not true when getting the CellGrid from the openpyxl reader. This means it also happens for other data types such as float and datetime, (e.g. destinations such as '3.14' or '07-06-2024')
